//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Работа_с_данными_2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public string phonenumber { get; set; }
        public string Email { get; set; }
    }
}
